### ISSUE TITLE
Issues with importing keras_nlp

### ISSUE THREAD

**Issue by anagraw** [awsaf49/detect-fake-text#1]
A lot of my friends were trying out your notebook, and faced a common problem when importing keras_nlp. Often stating circular importing as a problem. The fix to this is as follows: 
1. !pip uninstall keras keras-core keras-nlp
2. !pip install keras==2.15.0 keras-core==0.1.7 keras-nlp==0.6.3
3. Restart the session

Maybe we can add it as a comment in the notebook.

**Comment by awsaf49** [comment]
Thanks for letting me know. I think it is due to Keras V3 and V2 conflict issue. We can install them correctly by

```shell
!pip install —upgrade keras_nlp tensorflow
!pip install —upgrade keras
```

**Comment by awsaf49** [comment]
I'll add it on the code soon
